/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

/**
 * @author Sebastian Uyaguari
 * @author Denys Dutan
 * @author John Fárez
 * @author Santiago Cabrera
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    VentanaIniciarSesion ventanaIniciarSesion;
    VentanaCliente ventanCliente;
    VentanaBodega ventanaBodega;
    VentanaProductos ventanaProductos;
    VentanaFactura ventanaFactura;

    public VentanaPrincipal() {
        initComponents();

        ventanaIniciarSesion = new VentanaIniciarSesion();
        ventanCliente = new VentanaCliente();
        ventanaBodega = new VentanaBodega();
        ventanaProductos = new VentanaProductos();
        ventanaFactura = new VentanaFactura();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuItemIniciarSesion = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenuItem();
        menuItemProductos = new javax.swing.JMenuItem();
        menuItemFacturas = new javax.swing.JMenuItem();
        menuItemBodega = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menuItemEspaniol = new javax.swing.JMenuItem();
        menuItemIngles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");

        menuItemIniciarSesion.setMnemonic('o');
        menuItemIniciarSesion.setText("Iniciar Sesion ");
        menuItemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemIniciarSesion);

        menuItemSalir.setMnemonic('x');
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemSalir);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText(" Gestion");

        menuItemClientes.setMnemonic('t');
        menuItemClientes.setText("Gestion Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        editMenu.add(menuItemClientes);

        menuItemProductos.setMnemonic('y');
        menuItemProductos.setText("Gesion Productos");
        menuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProductosActionPerformed(evt);
            }
        });
        editMenu.add(menuItemProductos);

        menuItemFacturas.setMnemonic('p');
        menuItemFacturas.setText(" Gestion Facturas");
        menuItemFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFacturasActionPerformed(evt);
            }
        });
        editMenu.add(menuItemFacturas);

        menuItemBodega.setMnemonic('d');
        menuItemBodega.setText("Gestion bodegas");
        menuItemBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBodegaActionPerformed(evt);
            }
        });
        editMenu.add(menuItemBodega);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Idioma");

        menuItemEspaniol.setMnemonic('c');
        menuItemEspaniol.setText("Español");
        helpMenu.add(menuItemEspaniol);

        menuItemIngles.setMnemonic('a');
        menuItemIngles.setText("Ingles");
        helpMenu.add(menuItemIngles);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBodegaActionPerformed

        desktopPane.add(ventanaBodega);
        ventanaBodega.setVisible(true);

    }//GEN-LAST:event_menuItemBodegaActionPerformed

    private void menuItemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIniciarSesionActionPerformed

        desktopPane.add(ventanaIniciarSesion);
        ventanaIniciarSesion.setVisible(true);


    }//GEN-LAST:event_menuItemIniciarSesionActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed

        desktopPane.add(ventanCliente);
        ventanCliente.setVisible(true);

    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProductosActionPerformed

        desktopPane.add(ventanaProductos);
        ventanaProductos.setVisible(true);


    }//GEN-LAST:event_menuItemProductosActionPerformed

    private void menuItemFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFacturasActionPerformed

        desktopPane.add(ventanaFactura);
        ventanaFactura.setVisible(true);


    }//GEN-LAST:event_menuItemFacturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemBodega;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemEspaniol;
    private javax.swing.JMenuItem menuItemFacturas;
    private javax.swing.JMenuItem menuItemIngles;
    private javax.swing.JMenuItem menuItemIniciarSesion;
    private javax.swing.JMenuItem menuItemProductos;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables

}
